### PR TITLE
Spaces in url

### LINKED ISSUE #1: SPACES IN THE URLS OMG
http://localhost:4000/Pointers%20Gone%20Wild

are we okay with spaces?

### PR DESCRIPTION
**Pull request by bchong95**
Resolves #1

### CODE REVIEW

**Comment by bchong95** [comment]
@dpzmick Please Review :)

**Comment by dpzmick** [comment]
is the permalink field in the frontmatter and the url field in the mps/labs json files the only link between the two?

As in, the Title in the front matter doesn't matter?

**Comment by dpzmick** [comment]
I see what's going on. Looks good to me, although the (needed) url field might actually make things a touch messier :(

**Comment by bchong95** [comment]
Yeah. So you can create a page with the title "Text Editor" with the permalink can be "secret_url_for_course_staff".

**Pull request merged**
